import { requireUser } from "@/lib/auth/dal";
import { db } from "@/lib/db";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ActionButtonForm } from "@/components/form-feedback";
import { UserForm, ResetPinForm } from "@/components/admin/user-form";
import { updateUserStatus } from "@/features/users/actions";
import { formatDate } from "@/lib/utils";

export const metadata = { title: "Pengguna" };
export default async function UsersPage() {
  await requireUser(["ADMIN"]); const users = await db.user.findMany({ orderBy: [{ status: "asc" }, { createdAt: "desc" }] });
  return <><PageHeader eyebrow="Administrasi" title="Manajemen pengguna" description="Buat akun, atur akses, nonaktifkan akun, dan reset PIN." /><div className="grid gap-6 xl:grid-cols-[380px_1fr]"><Card className="h-fit"><CardHeader><h2 className="font-bold">Tambah pengguna</h2></CardHeader><CardContent><UserForm /></CardContent></Card><div className="grid content-start gap-3 md:hidden">{users.map((user) => <article key={user.id} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="break-words text-lg font-bold text-slate-950">{user.name}</h2><p className="break-all text-base text-slate-700">{user.email}</p><div className="mt-3 flex flex-wrap gap-2"><Badge tone={user.role === "ADMIN" ? "danger" : user.role === "TEACHER" ? "info" : "neutral"}>{user.role}</Badge><Badge tone={user.status === "ACTIVE" ? "success" : "neutral"}>{user.status}</Badge></div><p className="mt-3 text-base text-slate-700">Dibuat {formatDate(user.createdAt)}</p><div className="mt-4 flex flex-wrap gap-2"><ActionButtonForm action={updateUserStatus} fields={{ id: user.id, status: user.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" }} pendingLabel={user.status === "ACTIVE" ? "Menonaktifkan…" : "Mengaktifkan…"} size="sm" variant={user.status === "ACTIVE" ? "ghost" : "outline"}>{user.status === "ACTIVE" ? "Nonaktifkan" : "Aktifkan"}</ActionButtonForm><ResetPinForm userId={user.id} /></div></article>)}</div><div className="table-wrap hidden md:block"><table className="data-table"><thead><tr><th>Pengguna</th><th>Role</th><th>Status</th><th>Dibuat</th><th>Aksi</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong className="block text-slate-900">{user.name}</strong><span className="text-xs text-slate-500">{user.email}</span></td><td><Badge tone={user.role === "ADMIN" ? "danger" : user.role === "TEACHER" ? "info" : "neutral"}>{user.role}</Badge></td><td><Badge tone={user.status === "ACTIVE" ? "success" : "neutral"}>{user.status}</Badge></td><td>{formatDate(user.createdAt)}</td><td><div className="grid gap-2"><ActionButtonForm action={updateUserStatus} fields={{ id: user.id, status: user.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" }} pendingLabel={user.status === "ACTIVE" ? "Menonaktifkan…" : "Mengaktifkan…"} size="sm" variant={user.status === "ACTIVE" ? "ghost" : "outline"}>{user.status === "ACTIVE" ? "Nonaktifkan" : "Aktifkan"}</ActionButtonForm><ResetPinForm userId={user.id} /></div></td></tr>)}</tbody></table></div></div></>;
}
