export const COVER_ASPECT = 16 / 9;
export const COVER_WIDTH = 1280;
export const COVER_HEIGHT = 720;
export const COVER_QUALITY = 0.82;
export const MAX_COVER_SOURCE_BYTES = 5 * 1024 * 1024;
export const MAX_COVER_OUTPUT_BYTES = 2 * 1024 * 1024;
export const MAX_COVER_SOURCE_PIXELS = 20_000_000;
export const COVER_UPLOAD_URL_EXPIRY_SECONDS = 15 * 60;
export const COVER_SOURCE_TYPES = ["image/jpeg", "image/png", "image/webp"];
