import Link from "next/link";
import { BookOpen, CheckCircle2, ClipboardCheck, FolderTree, GraduationCap, Users, Video } from "lucide-react";
import { requireUser } from "@/lib/auth/dal";
import { db } from "@/lib/db";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CourseCard } from "@/components/courses/course-card";
import { EmptyState } from "@/components/empty-state";
import { formatDate } from "@/lib/utils";

export const metadata = { title: "Dashboard" };
export default async function DashboardPage() {
  const user = await requireUser();
  if (user.role === "ADMIN") return <AdminDashboard />;
  if (user.role === "TEACHER") return <TeacherDashboard user={user} />;
  return <StudentDashboard user={user} />;
}
async function AdminDashboard() {
  const [users, teachers, students, categories, courses, pending] = await Promise.all([db.user.count(), db.user.count({ where: { role: "TEACHER", status: "ACTIVE" } }), db.user.count({ where: { role: "STUDENT", status: "ACTIVE" } }), db.category.count({ where: { isActive: true } }), db.course.count({ where: { status: "PUBLISHED" } }), db.submission.count({ where: { status: "SUBMITTED" } })]);
  return <><PageHeader eyebrow="Ringkasan sistem" title="Dashboard administrator" description="Pantau pengguna, katalog pembelajaran, dan aktivitas review dari satu tempat." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total pengguna" value={users} hint={`${teachers} teacher · ${students} student`} icon={Users} /><StatCard label="Kategori aktif" value={categories} icon={FolderTree} tone="indigo" /><StatCard label="Course terbit" value={courses} icon={Video} tone="emerald" /><StatCard label="Menunggu review" value={pending} icon={ClipboardCheck} tone="amber" /></div><div className="mt-6 grid gap-5 md:grid-cols-3">{[["Kelola pengguna","Buat teacher/student dan atur status akun.","/admin/users"],["Susun kategori","Pertahankan katalog materi tetap rapi.","/admin/categories"],["Audit course","Lihat seluruh course dari semua teacher.","/admin/courses"]].map(([title,text,href]) => <Card key={href}><CardContent><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><Link className="mt-4 inline-flex text-sm font-semibold text-cyan-700" href={href}>Buka pengelolaan →</Link></CardContent></Card>)}</div></>;
}
async function TeacherDashboard({ user }) {
  const [courses, learnerCount, pending, reviewed] = await Promise.all([db.course.findMany({ where: { teacherId: user.id, status: { not: "ARCHIVED" } }, include: { category: true, teacher: true, _count: { select: { enrollments: true } } }, orderBy: { updatedAt: "desc" }, take: 4 }), db.enrollment.count({ where: { course: { teacherId: user.id } } }), db.submission.count({ where: { course: { teacherId: user.id }, status: "SUBMITTED" } }), db.review.count({ where: { submission: { course: { teacherId: user.id } }, status: "PUBLISHED" } })]);
  return <><PageHeader eyebrow="Teacher workspace" title={`Halo, ${user.name}`} description="Kelola materi demonstrasi dan tindak lanjuti submission student." actions={<Link href="/teacher/courses/new" className="inline-flex h-11 items-center rounded-xl bg-cyan-500 px-4 text-sm font-semibold text-slate-950">Buat course</Link>} /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Course aktif" value={courses.length} icon={Video} /><StatCard label="Total learner" value={learnerCount} icon={GraduationCap} tone="indigo" /><StatCard label="Perlu direview" value={pending} hint={`${reviewed} review dipublikasikan`} icon={ClipboardCheck} tone="amber" /></div><div className="mt-7 flex items-center justify-between"><h2 className="text-lg font-bold">Course terbaru</h2><Link href="/teacher/courses" className="text-sm font-semibold text-cyan-700">Lihat semua</Link></div>{courses.length ? <div className="mt-4 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{courses.map((course) => <CourseCard course={course} key={course.id} />)}</div> : <div className="mt-4"><EmptyState icon={Video} title="Belum ada course" description="Buat course pertama dan upload video demonstrasi." /></div>}</>;
}
async function StudentDashboard({ user }) {
  const [available, enrollments, latestSubmissions] = await Promise.all([db.course.count({ where: { status: "PUBLISHED", category: { isActive: true } } }), db.enrollment.findMany({ where: { studentId: user.id }, include: { course: { include: { category: true, teacher: true } } }, orderBy: { lastOpenedAt: "desc" }, take: 4 }), db.submission.findMany({ where: { studentId: user.id }, include: { course: true, review: true }, orderBy: { createdAt: "desc" }, take: 4 })]);
  const progressRows = enrollments.length ? await db.watchProgress.findMany({ where: { studentId: user.id, courseId: { in: enrollments.map((item) => item.courseId) } } }) : [];
  const progress = new Map(progressRows.map((item) => [item.courseId, item.percent])); const passed = latestSubmissions.filter((item) => item.review?.outcome === "PASSED").length;
  return <><PageHeader eyebrow="Student dashboard" title={`Siap berlatih, ${user.name.split(" ")[0]}?`} description="Lanjutkan course terakhir atau mulai materi baru dari katalog." /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Course tersedia" value={available} icon={BookOpen} /><StatCard label="Sedang dipelajari" value={enrollments.filter((item) => !item.completedAt).length} icon={Video} tone="indigo" /><StatCard label="Course lulus" value={passed} icon={CheckCircle2} tone="emerald" /></div><div className="mt-7 flex items-center justify-between"><h2 className="text-lg font-bold">Terakhir dibuka</h2><Link href="/courses" className="text-sm font-semibold text-cyan-700">Jelajahi course</Link></div>{enrollments.length ? <div className="mt-4 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{enrollments.map(({ course }) => <CourseCard key={course.id} course={course} progress={progress.get(course.id) || 0} />)}</div> : <div className="mt-4"><EmptyState icon={BookOpen} title="Belum mulai belajar" description="Buka katalog dan pilih course yang ingin dipelajari." /></div>}
    {latestSubmissions.length ? <Card className="mt-7"><CardHeader><h2 className="font-bold">Aktivitas submission</h2></CardHeader><CardContent className="grid gap-3">{latestSubmissions.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><strong className="text-sm">{item.course.title}</strong><p className="text-xs text-slate-500">Attempt {item.attemptNumber} · {formatDate(item.createdAt)}</p></div><Badge tone={item.review?.outcome === "PASSED" ? "success" : item.review?.outcome === "REVISION_REQUIRED" ? "danger" : item.status === "SUBMITTED" ? "warning" : "neutral"}>{item.review?.outcome || item.status}</Badge></div>)}</CardContent></Card> : null}</>;
}
