"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Film, LoaderCircle, Scissors, Square, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Field, inputClass } from "@/components/ui/field";
import { formatDuration } from "@/lib/utils";
import { uploadVideoAsset } from "./video-uploader";

export function TrimEditor({ courseId, submissionId, sourceAssetId, durationSeconds, sourceSizeBytes = 0 }) {
  const router = useRouter(); const videoRef = useRef(null); const ffmpegRef = useRef(null); const [url, setUrl] = useState(""); const [start, setStart] = useState(0); const [end, setEnd] = useState(durationSeconds || 1); const [status, setStatus] = useState(""); const [progress, setProgress] = useState(0); const [pending, setPending] = useState(false);
  useEffect(() => { fetch(`/api/videos/${sourceAssetId}/playback-url`).then((response) => response.json()).then((result) => setUrl(result.data?.url || "")).catch(() => {}); }, [sourceAssetId]);
  function preview() { const video = videoRef.current; if (!video) return; video.currentTime = start; video.play(); const check = () => { if (video.currentTime >= end || video.paused) { video.pause(); return; } requestAnimationFrame(check); }; requestAnimationFrame(check); }
  async function trim() {
    if (!(start >= 0 && end > start && end <= durationSeconds)) return toast.error("Rentang trim tidak valid."); setPending(true); setStatus("Memuat engine editor…");
    try {
      const [{ FFmpeg }, { fetchFile }] = await Promise.all([import("@ffmpeg/ffmpeg"), import("@ffmpeg/util")]); const ffmpeg = new FFmpeg(); ffmpegRef.current = ffmpeg;
      ffmpeg.on("progress", ({ progress: value }) => setProgress(Math.max(0, Math.min(70, Math.round(value * 70))))); ffmpeg.on("log", ({ message }) => { if (message.includes("frame=")) setStatus("Menyusun video hasil trim…"); });
      const multi = window.crossOriginIsolated; await ffmpeg.load(multi ? { coreURL: "/api/media-core?asset=mt-js", wasmURL: "/api/media-core?asset=mt-wasm", workerURL: "/api/media-core?asset=mt-worker" } : { coreURL: "/api/media-core?asset=single-js", wasmURL: "/api/media-core?asset=single-wasm" });
      setStatus("Mengunduh video ke editor browser…"); await ffmpeg.writeFile("input.mp4", await fetchFile(url)); const clipDuration = end - start;
      await ffmpeg.exec(["-ss", start.toFixed(3), "-i", "input.mp4", "-t", clipDuration.toFixed(3), "-c:v", "libx264", "-preset", "veryfast", "-crf", "23", "-pix_fmt", "yuv420p", "-c:a", "aac", "-movflags", "+faststart", "output.mp4"]);
      setStatus("Mengupload versi baru…"); const data = await ffmpeg.readFile("output.mp4"); const file = new File([data.buffer], `trim-${Date.now()}.mp4`, { type: "video/mp4" });
      await uploadVideoAsset({ courseId, purpose: "STUDENT_EDIT", file, durationSeconds: clipDuration, parentAssetId: sourceAssetId, submissionId, trimStartSeconds: start, trimEndSeconds: end, onProgress: (value) => setProgress(70 + Math.round(value * 0.3)) });
      ffmpeg.terminate(); ffmpegRef.current = null; toast.success("Hasil trim disimpan sebagai versi aktif."); router.refresh();
    } catch (error) { console.error(error); toast.error(error.message || "Editor kehabisan memori atau gagal memproses video."); } finally { setPending(false); setStatus(""); setProgress(0); }
  }
  function cancel() { ffmpegRef.current?.terminate(); ffmpegRef.current = null; setPending(false); setStatus(""); setProgress(0); }
  return <div className="grid gap-5"><div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><TriangleAlert className="mt-0.5 shrink-0" size={18}/><p>Editing berlangsung di perangkat Anda. File besar{sourceSizeBytes > 200 * 1024 * 1024 ? " ini melebihi 200 MB dan" : ""} dapat membutuhkan banyak memori dan waktu, khususnya pada mobile.</p></div>{url ? <video ref={videoRef} src={url} crossOrigin="anonymous" controls className="aspect-video w-full rounded-xl bg-black" /> : <div className="grid aspect-video place-items-center rounded-xl bg-slate-950 text-sm text-slate-400">Memuat video…</div>}<div className="grid gap-4 md:grid-cols-2"><Field label="Mulai (detik)"><input className={inputClass} type="number" min="0" max={end - 0.01} step="0.01" value={start} onChange={(event) => setStart(Number(event.target.value))} /></Field><Field label="Selesai (detik)"><input className={inputClass} type="number" min={start + 0.01} max={durationSeconds} step="0.01" value={end} onChange={(event) => setEnd(Number(event.target.value))} /></Field></div><div><div className="mb-2 flex justify-between text-xs text-slate-500"><span>{formatDuration(start, true)}</span><strong className="text-slate-800">Hasil: {formatDuration(end - start, true)}</strong><span>{formatDuration(end, true)}</span></div><input aria-label="Batas mulai trim" className="video-range w-full" type="range" min="0" max={durationSeconds} step="0.01" value={start} onChange={(event) => setStart(Math.min(Number(event.target.value), end - 0.01))} /><input aria-label="Batas akhir trim" className="video-range w-full" type="range" min="0" max={durationSeconds} step="0.01" value={end} onChange={(event) => setEnd(Math.max(Number(event.target.value), start + 0.01))} /></div>{pending ? <div><div className="mb-2 flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-600"><LoaderCircle className="animate-spin" size={15}/>{status}</span><strong>{progress}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-cyan-500 transition-all" style={{ width: `${progress}%` }} /></div></div> : null}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={preview} disabled={pending}><Film size={17}/> Preview trim</Button><Button type="button" onClick={trim} disabled={pending || !url}><Scissors size={17}/> Proses dan simpan</Button>{pending ? <Button type="button" variant="danger" onClick={cancel}><Square size={15}/> Batalkan</Button> : null}</div></div>;
}
